# Generated by Django 5.0.1 on 2024-01-31 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_usuario_alter_projeto_acao_no_sprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255, verbose_name='Nome da Atividade')),
                ('descricao', models.TextField(default='', verbose_name='Descrição da Atividade')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Horas Trabalhadas')),
                ('data_da_atividade', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Atividade')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto', verbose_name='Projeto')),
            ],
        ),
    ]
