# Generated by Django 5.0.1 on 2024-02-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_atividade_responsavel_atividade_status_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status_atividade',
            field=models.CharField(choices=[('Não Iniciado', 'Não Iniciado'), ('Em andamento', 'Em andamento'), ('Em Homologação', 'Em Homologação'), ('Parado', 'Parado'), ('Aguardando Terceiro', 'Aguardando Terceiro'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='', max_length=255, verbose_name='Status da Atividade'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Não Iniciado', 'Não Iniciado'), ('Em andamento', 'Em andamento'), ('Em Homologação', 'Em Homologação'), ('Parado', 'Parado'), ('Aguardando Terceiro', 'Aguardando Terceiro'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='', max_length=255, verbose_name='Status'),
        ),
    ]
